name: Build and release SDK
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+a*"
      - "v[0-9]+.[0-9]+.[0-9]+b*"
      - "v[0-9]+.[0-9]+.[0-9]+rc*"
      
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v5

      - name: Install packaging deps
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install build
          .venv/bin/python -m pip install twine

      - name: Build SDist and wheel
        run: .venv/bin/python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist/*

      - name: Check metadata
        run: .venv/bin/python -m twine check dist/*

  publish:
    needs: [dist]
    environment: pypi
    permissions:
      # Required for trusted publishing
      # https://docs.pypi.org/trusted-publishers/
      id-token: write
      # Required for generating attestations
      attestations: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@v1.4.3
        with:
          subject-path: "dist/*"

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: true